<?php

namespace App\Services\Network;

use App\Models\Nas;
use Illuminate\Support\Facades\File;

/**
 * Writes the per-NAS FreeRADIUS "virtual server" config (v0.6.5) — in
 * practice just two extra `listen{}` sockets bound to nas.auth_port/
 * acct_port, reusing the SAME `default` virtual server's authorize{}/
 * accounting{}/sql sections (a real separate `server nas-N { ... }` block
 * per NAS would mean duplicating all of that, for zero benefit — FreeRADIUS
 * lets multiple `listen{}` sockets share one server's processing sections
 * directly when they live inside the same file).
 *
 * Isolation between NAS is by PORT, not source IP (see the generated
 * clients file's own comment) — this is the whole reason "unique RADIUS
 * port per NAS" was locked in as this cluster's architecture back in
 * v0.6.1, instead of the far more common "one shared port, NAS
 * distinguished by source IP" RADIUS deployment shape: every NAS reaches
 * FreeRADIUS through one of several VPN node containers (v0.6.4 multi-node
 * pool) that all MASQUERADE onto their own boss-network IP, so source-IP
 * based client matching can't tell one NAS apart from another here.
 *
 * Files land on the freeradius_nas_config volume shared with the
 * freeradius container (docker-compose.yml) — actually opening the new
 * ports requires a radiusd restart, NOT a mere SIGHUP (verified for real
 * against the running container: a HUP-reloaded config with a brand new
 * `listen{}` section left the new port unbound — see CLAUDE.md v0.6.5).
 * That restart is driven entirely from INSIDE the freeradius container's
 * own entrypoint.sh supervisor loop (polls this same directory's content
 * hash every few seconds) — this class only ever writes files, it never
 * signals or execs into the freeradius container directly (no Docker
 * socket access, same stance as every other cross-container coordination
 * in this codebase).
 */
class FreeradiusVirtualServerService
{
    public function sync(Nas $nas): void
    {
        if ($nas->auth_port === null || $nas->acct_port === null) {
            // Guards a hypothetical legacy/edge row that predates the
            // allocator — every real NasService::create() call already
            // allocates both before this is ever reached.
            return;
        }

        File::ensureDirectoryExists($this->listenDir());
        File::ensureDirectoryExists($this->clientsDir());

        $clientsName = "nas_{$nas->id}_clients";

        File::put($this->clientsDir()."/nas-{$nas->id}.conf", <<<CONF
        # Generated by FreeradiusVirtualServerService — regenerated on every
        # NasService update, do not edit by hand.
        clients {$clientsName} {
            client nas_{$nas->id} {
                # boss-network as a whole, NOT the NAS's own VPN tunnel
                # internal_ip — every VPN node container MASQUERADEs NAS
                # traffic onto ITS OWN boss-network IP before it reaches
                # freeradius (hub-and-spoke isolation, CLAUDE.md v0.6.2),
                # so the packet's apparent source here is one of several
                # VPN node containers, never the NAS itself. The secret
                # below (unique per NAS) combined with the port this client
                # list is attached to (see listen/nas-{$nas->id}.conf) is
                # the real per-NAS security boundary, not this ipaddr.
                ipaddr = 172.28.0.0/24
                secret = "{$nas->radius_secret}"

                # Real production bug found debugging test-x-bajastu (v0.6.5
                # amendment): radiusd.conf's global `require_message_authenticator
                # = yes` (BlastRADIUS mitigation, on by default in this stock
                # image) silently DISCARDS any Access-Request lacking a
                # Message-Authenticator attribute — no log line at all, not
                # even a reject, confirmed via tcpdump showing the real packet
                # arriving intact at this container's own interface while
                # radiusd's own debug log never once recorded receiving it.
                # RouterOS's real PPP CHAP/MSCHAP Access-Requests do not
                # include Message-Authenticator (verified byte-for-byte via a
                # captured packet's hex dump), so EVERY real NAS auth attempt
                # was being silently dropped, indistinguishable from a normal
                # timeout — which is exactly why RouterOS never observed an
                # explicit reject and kept retrying instead of failing over.
                # Overriding it to "no" HERE (scoped to this one client, not
                # radiusd.conf's global default) is radiusd.conf's own
                # documented recommendation for exactly this situation — a
                # RADIUS client that hasn't been updated to send
                # Message-Authenticator. "auto" is NOT an option: radiusd.conf
                # explicitly states auto-detection has no effect for a client
                # defined by a network/mask (ours is a /24, not a single IP).
                require_message_authenticator = no
            }
        }
        CONF);

        File::put($this->listenDir()."/nas-{$nas->id}.conf", <<<CONF
        # Generated by FreeradiusVirtualServerService — regenerated on every
        # NasService update, do not edit by hand.
        listen {
            type = auth
            ipaddr = *
            port = {$nas->auth_port}
            clients = {$clientsName}
        }
        listen {
            type = acct
            ipaddr = *
            port = {$nas->acct_port}
            clients = {$clientsName}
        }
        CONF);
    }

    public function remove(Nas $nas): void
    {
        File::delete($this->listenDir()."/nas-{$nas->id}.conf");
        File::delete($this->clientsDir()."/nas-{$nas->id}.conf");
    }

    private function listenDir(): string
    {
        return config('services.freeradius.nas_config_dir').'/listen';
    }

    private function clientsDir(): string
    {
        return config('services.freeradius.nas_config_dir').'/clients';
    }
}
